In [1]:

import numpy as np

In [101]:

vector = [1,2,3,4,5]

# Vectors

* a one dimensional array
* when it becomes more than one array, it becomes a matrix

### Matrix
* a 2D or 3D array is called a matrix 


In [10]:
# This is a 2x3 matrix which is 2D , three columns 
matrix_2 = np.array([[1,2,3],[4,5,6]])
print(matrix_2)

[[1 2 3]
 [4 5 6]]


In [9]:
# 2D Array , 3x3 matrix
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# To get the shape of the array
matrix_2.shape

(2, 3)

In [15]:
matrix.shape

(3, 3)

### ones, zeros

In [22]:
ones = np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
zeros = np.zeros((4,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Accessing numpy arrays

* '''np.array[vertical index, horizontal index]'''   for one element 
* '''np.array[vertical start:end, horizontal start:end]'''    for more than one element 

In [26]:
matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
# top left element
matrix_2[0,0]

1

In [31]:
# first row
matrix_2[0,:]

array([1, 2, 3])

In [32]:
# first column
matrix_2[:,0]

array([1, 4])

In [33]:
# first two rows and first two columns
matrix_2[0:2,0:2]

array([[1, 2],
       [4, 5]])

### Boolean Indexing 

In [35]:
#select all values greater than 2
print(matrix_2 > 2)

[[False False  True]
 [ True  True  True]]


In [38]:
# selecting values greater than 2
matrix_2[matrix_2 > 2]

array([3, 4, 5, 6])

In [41]:
# selecting values less than  3, greater than 5
# merging multiple conditions

matrix_2[(matrix_2 < 3 ) | (matrix_2 > 5)]

array([1, 2, 6])

### Modifying Numpy Arrays

In [42]:
# adding an element to an array
matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# ADDING to a row
matrix_2_extra = np.append(matrix_2, [[92,88,70]], axis=0)
matrix_2_extra

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [92, 88, 70]])

In [49]:
# adding array to a colum
np_column = np.array([[92],[88],[70]])
np_column

array([[92],
       [88],
       [70]])

In [50]:
matrix_2_column = np.append(matrix_2_extra,np_column, axis=1)
matrix_2_column

array([[ 1,  2,  3, 92],
       [ 4,  5,  6, 88],
       [92, 88, 70, 70]])

In [55]:
# removing elements , removes the middle row 
matrix_delete = np.delete(matrix_2_column, [1], axis=0)
matrix_delete

array([[ 1,  2,  3, 92],
       [92, 88, 70, 70]])

### Methods (arange, reshape, linspace, eye)

In [57]:
#arnge

ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# steping by 2 using 'np.arange'
ar_step = np.arange(0,10,2)
ar_step

array([0, 2, 4, 6, 8])

In [60]:
# reshape
# can be used to reshape the look of an array

ar.shape

(10,)

In [65]:
ar_reshape = ar.reshape(2,5)
ar_reshape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [66]:
ar_reshape1 = ar.reshape(5,2)
ar_reshape1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
# linspace
# it allows for even spacing 
lin_space = np.linspace(0,20)
lin_space

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [73]:
lin_space = np.linspace(0,20,8)
lin_space

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [77]:
#eye 
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])



### Function: sum, min, ,ax, argmin, argmax

In [86]:
matrix_2

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
#sum
matrix_2.sum()

21

In [85]:
# sum of a row
matrix_2.sum(axis=1)

array([ 6, 15])

In [87]:
# sum of a column
matrix_2.sum(axis=0)

array([5, 7, 9])

In [89]:
#min of each row
matrix_2.min(axis=1)

array([1, 4])

In [90]:
#min of each column
matrix_2.min(axis=0)

array([1, 2, 3])

In [91]:
#max of each row
matrix_2.max(axis=1)

array([3, 6])

In [92]:
#max of each column
matrix_2.max(axis=0)

array([4, 5, 6])

In [95]:
#max of each column
matrix_2.max(axis=0)

array([4, 5, 6])

In [96]:
#Index of min of each row
matrix_2.argmin(axis=1)

array([0, 0])

In [97]:
#Index of min of each column
matrix_2.argmin(axis=0)

array([0, 0, 0])

In [99]:
#Index of max of each row
matrix_2.argmax(axis=1)

array([2, 2])

In [100]:
#Index of max of each column
matrix_2.argmax(axis=0)

array([1, 1, 1])

### Random: rand, randn, randint

In [103]:
# rand: 0 & 1
rand_arr = np.random.rand(3,4)
rand_arr

array([[0.59752202, 0.00411583, 0.89087412, 0.24154471],
       [0.60378125, 0.88517302, 0.6295384 , 0.51635957],
       [0.75656122, 0.03311269, 0.24222701, 0.83776872]])

In [105]:
# random: from standard normal distribution
rand_arr_n = np.random.randn(3,3)
rand_arr_n

array([[-0.38193692,  2.18079397, -1.57360078],
       [ 3.33647646,  0.59582055,  0.83678317],
       [ 1.09081522, -1.23253595,  0.43877124]])

In [115]:
# randint: 1 - 10
randint_arr = np.random.randint(1,10, size=(3,5))
randint_arr

array([[8, 8, 8, 4, 7],
       [1, 1, 9, 6, 2],
       [6, 7, 7, 4, 3]])


# When is numpay arrays useful ?

### numpy arrays are used when carrying out a multidimensional connotations
### Calculations on data that are within the same data type 
### integers, numerical data
